version: "3"
services:
  authors:
    build: ./authors
    container_name: authors-service
    ports:
      - 8081:8081
    environment:
      - JAEGER_HOST=jaeger
      - REDIS_HOST=redis
    depends_on:
      - redis
      - jaeger
    networks:
      - mynet
  books:
    build: ./books
    container_name: books-service
    ports:
      - 8082:8082
    environment:
      - JAEGER_HOST=jaeger
      - REDIS_HOST=redis
    networks:
      - mynet
    depends_on:
      - redis
      - jaeger
  frontend:
    build: ./frontend
    container_name: frontend-service
    ports:
      - 8083:8083
    environment:
      - JAEGER_HOST=jaeger
      - REDIS_HOST=redis
      - AUTHORS_HOST=authors
      - AUTHORS_PORT=8081
      - BOOKS_HOST=books
      - BOOKS_PORT=8082
    networks:
      - mynet
    depends_on:
      - redis
      - jaeger

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - mynet
  jaeger:
    image: jaegertracing/all-in-one:1.22
    container_name: jaeger
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
    networks:
      - mynet

networks:
  mynet:
